services:
  - type: web
    name: ring4-nova-sonic-server
    env: node
    buildCommand: cd nova-sonic-server && npm ci --production
    startCommand: cd nova-sonic-server && node server.js
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
    healthCheckPath: /health