services:
  - type: web
    name: ring4-nova-sonic-server
    env: node
    repo: https://github.com/joseph-karim/ring4-site.git
    rootDir: .
    buildCommand: cd nova-sonic-server && npm install
    startCommand: cd nova-sonic-server && npm start
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
    healthCheckPath: /health